### ISSUE TITLE
No se que hacer con esto...

### ISSUE THREAD

**Issue by ISInfinity98** [CTPache/ParcheadorAAT#1]
Cuando ejecuto el programa PatcherNew.exe pasa esto todo el rato y el menu del parcheador no llega a abrirse nunca.

![image](https://user-images.githubusercontent.com/81447007/121614649-734c0d80-ca5f-11eb-99b7-901bf91753b8.png)

**Comment by shootlazer** [comment]
Porque no detecta la ruta de instalación del juego en el registro.

**Comment by WorstAquaPlayer** [comment]
Tienes que tener el juego instalado por Steam. Ten en cuenta que si lo has instalado en una carpeta y luego haberlo movido de manera manual a otra, el parcheador fallara

**Comment by CTPache** [comment]
He actualizado el Readme.md explicando por qué puede pasar esto. Probablemente haga otro documento más detallado con varios casos de fallo, y cierro el issue
