### ISSUE TITLE
Un pequeño error gráfico.

### ISSUE THREAD

**Issue by Jeptioak** [CTPache/ParcheadorAAT#3]
Cuando tienes que presentar el paradero de Redd White en el plano, la "M" de "_murderer_" aparece en vez de la "A" de "asesino". Segundo caso, segundo día, primer juego.
![20210611101947_1](https://user-images.githubusercontent.com/74663954/121762988-8a8e0800-cafe-11eb-8fc0-7496e0bc705e.jpg)
![20210611101858_1](https://user-images.githubusercontent.com/74663954/121762990-8b269e80-cafe-11eb-9386-5c22e0723337.jpg)

**Comment by CTPache** [comment]
Corregido, cierro el issue cuando salga la siguiente release.
