### ISSUE TITLE
Alemán.

### ISSUE THREAD

**Issue by Jeptioak** [CTPache/ParcheadorAAT#5]
La "carta de presentación" sigue en alemán. Quinto caso, primer día, primer juego.
![20210616192212_1](https://user-images.githubusercontent.com/74663954/122312094-23df6480-ced9-11eb-9669-1543ae4744ac.jpg)

**Comment by WorstAquaPlayer** [comment]
Corregido. Gracias por reportarlo, se cerrara el issue cuando salga la siguiente release.
