### ISSUE TITLE
Bug de texto en Caso 4

### ISSUE THREAD

**Issue by Malopextremo** [CTPache/ParcheadorAAT#6]
En el Episodio 4 - Día 3: Investigación, en la zona de Archivos, hay un bug de texto que ocurre al examinar la zona derecha de la pantalla.

https://user-images.githubusercontent.com/86098597/122523899-89207c00-cfe5-11eb-9258-4f9741629852.mp4

**Comment by WorstAquaPlayer** [comment]
Corregido. Gracias por reportarlo, se cerrara el issue cuando salga la siguiente release.
