### ISSUE TITLE
Continuar partida  

### ISSUE THREAD

**Issue by JosiasMata7** [CTPache/ParcheadorAAT#9]
El botón de continuar no aparece cuando cambio el idioma de inglés a español, solo puedo empezar una nueva partida
![image](https://user-images.githubusercontent.com/89634001/131098428-f47338f7-5967-415b-95a4-f59beae1842e.png)

**Comment by WorstAquaPlayer** [comment]
Esto se debe a que el juego utiliza partidas guardadas por cada idioma, es decir, si guardas en el idioma francés, la partida guardada no aparecerá en el idioma alemán (y demás).
